### ISSUE TITLE
Usefulness with original 1part brass nut?

### ISSUE THREAD

**Issue by 3DSTB** [emard/linactuator#4]
I already have a brass nut on the top part of the z-screw with almost no play.  
![nut](https://user-images.githubusercontent.com/25535486/40715737-d95b4752-6406-11e8-821d-d0cc4ff66f76.png)
Is it still usefull to upgrade to the linactuator? 

My brass nut is in a black plastic housing and this is mounted with 4 screws from the top. Why are there 4 screws on the bottom of the linactuator?

**Comment by emard** [comment]
HI

This original assembly will slowly degrade over time, let's say
after printing first 1kg of filament it will surely need maintenance.

If zleveler is used, It won't work correctly first layer wont stick
reliably.

Lower 4 screws are for the plastic cover that completely closes linactuator
from bottom side, it should be 3D printed too otherwise brass nut will
leave it :)

**Comment by 3DSTB** [comment]
Hi,
thanks. Here is a drawing as i understand it now:
![sketch](https://user-images.githubusercontent.com/25535486/40717504-d87fef80-640c-11e8-99fc-d298b44e236f.png)
I found here that the spring should be 1cm long:
http://radiona.org/wiki/inventory/fabrikator_2_mini
Is that correct and not to short? Or must the bottom-nut not touch the bottom cover?

Another question is: would be longer nuts better (maybe only the top nut)? Here is an example nut:
https://grabcad.com/library/hexagon-nut-din-6334

Can you please upload the file for the bottom Cover?

FYI, i upgraded the mounting for the brass rubber bearing: 
![mounting](https://user-images.githubusercontent.com/25535486/40717994-ab44dd12-640e-11e8-82bd-b20f20fd8fae.png)

**Comment by emard** [comment]
Yes that schematics depcits correct assembly and spring must
really be

1. short (0.5-1 cm)
2. weak spring (weakest possible force per mm of compression)

The spring crompression should be very little, maybe 1 mm.
If spring is compressed too tight, friction and material wear
will increase without any other benefit to the function.

Normally it is possible to cut springs short, and it will also work

If spring is too long then whole actuactor must be longer and
it won't fit to the 3D printer Z axis

**Comment by 3DSTB** [comment]
Tanks!
What is the reference for the spring length (should the compressed or the uncompressed length be 0.5 to 1cm)?

**Comment by emard** [comment]
For fixed spring length, you can experiment 3D printing
varoios actuator lengths or spacers to adjust optimal length
to given spring.

You will feel it on your hand the Z-leadscrew
assembly is easy to rotate without any significant
friction and the should have zero "airgap" in up-down direction
so small that is impossible to feel it by the hand.

If it's too hard to rotate or has the gap, rotate one of the nuts and
try again. If can't go this way, then decrease spring compression strength

**Comment by 3DSTB** [comment]
Ok, i have now a spring which is 0.8x6x10 which is may be ok. There is enough  room to play with the compression.

**Comment by emard** [comment]
Yes yes also when you print actuator, check that nuts
shake loose inside without spring. If neccessary, increase
hexagonal hole inside to avoid any friction to the nuts.

**Comment by 3DSTB** [comment]
Last question:
Can you please upload your scad file for the plastic cover? May it is easier to just modify your file.
Thanks!

**Comment by emard** [comment]
It is on the scad already, check out the source
